"""Tool generator that creates native Dulus tools from Composio schemas."""
import json
import re
from pathlib import Path
from typing import Any, Dict, Optional


def _slug_to_func_name(slug: str) -> str:
    """Convert a Composio tool slug to a valid Python function name."""
    return re.sub(r"[^a-zA-Z0-9_]", "_", slug.lower()).strip("_")


def generate_tool_py(
    tool_slug: str,
    schema: Dict[str, Any],
    output_dir: Path,
    session_id: Optional[str] = None,
    user_id: Optional[str] = None,
) -> Path:
    """Generate a standalone Dulus tool for a Composio operation."""
    func_name = _slug_to_func_name(tool_slug)
    file_name = f"{func_name}.py"
    output_path = output_dir / file_name

    description = schema.get("description", f"Execute {tool_slug} via Composio")
    params = schema.get("parameters", schema.get("input_schema", {})).get("properties", {})
    param_unpack = ", ".join(
        f"{name!r}: params.get({name!r})" for name in params
    )

    code = f'''"""Auto-generated Dulus tool for Composio: {tool_slug}
Generated by the Dulus Composio plugin.
"""
import sys
import json
from pathlib import Path

# Ensure composio is available
sys.path.insert(0, str(Path.home() / ".dulus" / "plugins" / "composio"))
from composio_plugin.session_manager import get_or_create_session


def {func_name}(params: dict, config: dict) -> str:
    {description!r}
    session = get_or_create_session(
        user_id={repr(user_id or "dulus_user")},
        toolkits=["gmail"],  # TODO: infer from tool slug
    )
    result = session.execute(
        tool_slug={repr(tool_slug)},
        arguments= {{{param_unpack}}}
    )
    data = result.data if hasattr(result, "data") else result
    return json.dumps(data, indent=2, default=str)


# Standalone test
if __name__ == "__main__":
    test_params = {{
        # Fill with required params
    }}
    print({func_name}(test_params, {{}}))
'''
    output_path.write_text(code, encoding="utf-8")
    return output_path


def generate_plugin_tool_py(
    tool_defs: list,
    output_path: Path,
) -> Path:
    """Generate a plugin_tool.py exporting multiple ToolDefs."""
    header = '''"""Auto-generated Composio plugin_tool.py
Generated by the Dulus Composio plugin.
"""
import sys
import json
from pathlib import Path

PLUGIN_DIR = Path(__file__).parent.absolute()
if str(PLUGIN_DIR) not in sys.path:
    sys.path.insert(0, str(PLUGIN_DIR))

from tool_registry import ToolDef
from composio_plugin.session_manager import get_or_create_session, get_client

'''

    functions = []
    tooldefs = []

    for td in tool_defs:
        slug = td["slug"]
        func_name = _slug_to_func_name(slug)
        desc = td.get("description", f"Execute {slug}")
        params = td.get("schema", {}).get("properties", {})
        required = td.get("schema", {}).get("required", [])

        param_unpack = ", ".join(
            f"{name!r}: params.get({name!r})" for name in params
        )

        func = f'''
def {func_name}(params: dict, config: dict) -> str:
    {desc!r}
    session = get_or_create_session(user_id="dulus_user", toolkits=["gmail"])
    result = session.execute(tool_slug={repr(slug)}, arguments={{{param_unpack}}})
    data = result.data if hasattr(result, "data") else result
    return json.dumps(data, indent=2, default=str)
'''
        functions.append(func)

        schema = {
            "name": slug,
            "description": desc,
            "input_schema": {
                "type": "object",
                "properties": params,
                "required": required
            }
        }
        tooldefs.append(f'''    ToolDef(
        name={repr(slug)},
        schema={schema},
        func={func_name}
    )''')

    footer = f'''

TOOL_DEFS = [
{",".join(tooldefs)}
]
TOOL_SCHEMAS = [t.schema for t in TOOL_DEFS]
'''

    output_path.write_text(header + "".join(functions) + footer, encoding="utf-8")
    return output_path
