"""Tests for the code emitted by the bundled Composio plugin."""

from data.plugins.composio.composio_plugin.tool_generator import (
    generate_plugin_tool_py,
    generate_tool_py,
)


SAMPLE_SCHEMA = {
    "description": 'Send an email containing "quoted" text.',
    "parameters": {
        "properties": {
            "to": {"type": "string"},
            "body-text": {"type": "string"},
        },
        "required": ["to"],
    },
}


def test_standalone_composio_tool_is_valid_python(tmp_path):
    output = generate_tool_py("GMAIL_SEND_EMAIL", SAMPLE_SCHEMA, tmp_path)
    generated = output.read_text(encoding="utf-8")

    compile(generated, str(output), "exec")

    assert "Generated by the Dulus Composio plugin" in generated
    assert 'Path.home() / ".dulus" / "plugins"' in generated
    assert "'to': params.get('to')" in generated
    assert "'body-text': params.get('body-text')" in generated
    assert "Falcon" not in generated


def test_multi_tool_composio_plugin_is_valid_python(tmp_path):
    output = tmp_path / "plugin_tool.py"
    tool_defs = [
        {
            "slug": "GMAIL_SEND_EMAIL",
            "description": 'Send an email containing "quoted" text.',
            "schema": SAMPLE_SCHEMA["parameters"],
        },
        {
            "slug": "CALENDAR_CREATE_EVENT",
            "description": "Create an event.\nAccepts a title and start time.",
            "schema": {
                "properties": {
                    "title": {"type": "string"},
                    "start": {"type": "string"},
                },
                "required": ["title", "start"],
            },
        },
    ]

    generate_plugin_tool_py(tool_defs, output)
    generated = output.read_text(encoding="utf-8")

    compile(generated, str(output), "exec")

    assert "'to': params.get('to')" in generated
    assert "'start': params.get('start')" in generated
    assert "GMAIL_SEND_EMAIL" in generated
    assert "CALENDAR_CREATE_EVENT" in generated
